name: "Test Report"
on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
permissions:
    contents: read
    actions: read
    checks: write
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - name: Test Summary
              uses: test-summary/action@v2
              with:
                  paths: "*.xml"
              if: always()
            # - uses: dorny/test-reporter@v2
            #   with:
            #       artifact: test-results
            #       name: Tests
            #       path: "*.xml"
            #       reporter: java-junit
