name: "Test Report"
on:
    workflow_run:
        workflows: ["CI"]
        types:
            - completed
permissions:
    contents: read
    actions: read
    checks: write
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - name: download test results artifact
              uses: actions/download-artifact@v5
              with:
                  name: test-results
                  run-id: ${{ github.event.workflow_run.id }}
                  github-token: ${{ secrets.GITHUB_TOKEN }}
            - id: parse_tests
              name: parse test results
              uses: m-ringler/get-xpath@v3
              with:
                  xml-file: "test-results.xml"
                  xpath: "//testsuites/@tests"
            - id: parse_failures
              name: parse test results
              uses: m-ringler/get-xpath@v3
              with:
                  xml-file: "test-results.xml"
                  xpath: "//testsuites/@failures"
            - name: Update test-results gist
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                  auth: ${{ secrets.GIST_SECRET }}
                  gistID: 26882516c7ac38bf94a81784f966bd86
                  filename: node-api-zig-test-badge.json
                  label: "test"
                  namedLogo: "zig"
                  message: "${{steps.parse_tests.outputs.info}} tests / ${{steps.parse_failures.outputs.info}} failures"
                  color: "#F7A41D"
